#!/bin/bash
set -e
#--------------------------------------------------------------------------------
# SCRIPT TO OBTAIN C-STAR BLUEPRINTS
# This program will donwload necessary code and input files to run C-Star in a
# particular blueprint

# It is necessary to have performed a first-time setup using the script "setup"
#--------------------------------------------------------------------------------
if [[ "$#" -eq 0 || "$1" == "-h" || "$1" == "--help" ]];then    
    echo "
	Usage: $(basename "$0") [blueprint_name]

	Description:
		Obtain code and input files related to a particular C-Star blueprint and compile.		
	
      	Options:
	-h, --help : Display this help message

	blueprint_name : 
		roms_marbl_example : 24x24 example blueprint of ROMS with MARBL biogeochemistry
	"
    exit 0
fi

case "$1" in
    roms_marbl_example)
	blueprintdir=${CSTAR_ROOT}/blueprints/roms_marbl_example
	# Download ROMS source code:
	git clone https://github.com/CWorthy-ocean/cstar_blueprint_roms_marbl_example ${blueprintdir}
	#git -C ${CSTAR_ROOT}/configurations/roms_marbl_example checkout --quiet roms_latest

	# Compile
	cd ${blueprintdir}/code
	cp ${ROMS_ROOT}/Work/Makefile .
	if [[ ${CSTAR_SYSTEM} == *"_gnu" ]];then
	    make COMPILER=gnu
	else
	    make
	fi
	if [ -L input_data ];then rm input_data;fi
	cd ${blueprintdir}; ln -s code/roms .
	echo "--------------------------------------------------------------------------------"
	echo "$1 download and compile complete. See "
	echo "${CSTAR_ROOT}/blueprints/roms_marbl_example/README.md"
	echo "for instructions on how to run".
	echo "--------------------------------------------------------------------------------"
	;;
    *)
	echo "Unsupported blueprint name: $1. For a list of valid options, run"
	echo "./cstar_get_blueprint --help"
esac
	    
	
	# Download initial and boundary files:
	
