#!/bin/bash
set -e
#--------------------------------------------------------------------------------
# SCRIPT FOR FIRST TIME SETUP
# This program will acquire the necessary codebases, create an environment for
# your machine, and set up libraries necessary to run

# To set up a specific blueprint, use the cstar_get_blueprint script
#--------------------------------------------------------------------------------
if [[ "$#" -eq 0 || "$1" == "-h" || "$1" == "--help" ]];then    
    echo "
	Usage: $(basename "$0") [target_machine]

	Description:
		Set up C-Star for the first time on a machine. This script creates an environment
		in which to install and  run C-Star, and obtains and compiles external codebases.

		After successful setup:
		      - activate the C-Sar environment at any time using 'cstar_env'
      		      - Run 'cstar_get_blueprint' to obtain specific instances of C-Star
		
	
      	Options:
	-h, --help : Display this help message

	target_machine : 
		osx_arm64_gnu          : Install C-Star on an (M2) Mac with Apple Silicon (ARM64 architecture)
		                      using GNU toolchain via Conda
		sdsc_expanse_intel     : Install C-Star on SDSC's Expanse HPC using Intel toolchain
				      via Environment Modules
		sdsc_expanse_gnu       : Install C-Star on SDSC's Expanse HPC using GNU toolchain
				      via Environment Modules
		ncar_derecho_intel     : Install C-Star on NCAR's Derecho HPC using Intel toolchain	
				      via Environment Modules
		nersc_perlmutter_intel : Install C-Star on NERSC's perlmutter HPC using Intel toolchain
				      via Environment Modules
		nersc_perlmutter_gnu : Install C-Star on NERSC's perlmutter HPC using GNU toolchain
				      via Environment Modules

	"
    exit 0
fi

cstar_setupdir=$(pwd)

################################################################################
# MACHINE SPECIFIC COMMANDS AND VARIABLE SETTINGS
case "$1" in
    osx_arm64_gnu)
	# 1. Set up environment
	# Check if env exists, install if not
	if [ -d conda_envs/cstar_gnu ] ;
	then echo "conda environment exists.
       	   	If you have already run this setup script and
       	       	 are experiencing problems with the environment
		 then remove it using"
	     echo "conda env remove -p $(pwd)/conda_envs/cstar_gnu"
	     echo "and try running this script again"
	else
	    cstarenv="$(pwd)/conda_envs/cstar_gnu/"
	    conda env create -f conda_envs/cstar_gnu.yml --prefix="${cstarenv}"
	    
	    source $(conda info --base)/etc/profile.d/conda.sh
	    conda activate "${cstarenv}"	    

	    # Trim prefix in shell PS1 to just env dirname, not full path	    
	    conda config --set env_prompt '({name})'
	    # ii. SET ENVIRONMENT VARIABLES
	    conda env config vars set ROMS_ROOT="$(pwd)/externals/ucla-roms/" -p "${cstarenv}" > /dev/null
	    conda env config vars set MARBL_ROOT="$(pwd)/externals/MARBL/" -p "${cstarenv}" > /dev/null
	    conda env config vars set CSTAR_ROOT="$(dirname $(pwd))" -p "${cstarenv}" > /dev/null
	    conda env config vars set NETCDFHOME="${cstarenv}" -p "${cstarenv}" > /dev/null
	    conda env config vars set MPIHOME="${cstarenv}" -p "${cstarenv}" > /dev/null
	    conda env config vars set CSTAR_SYSTEM="$1" -p "${cstarenv}" > /dev/null
	    conda activate "${cstarenv}" # The following are dependent on previous env vars so need to activate to see them
	    conda env config vars set LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$NETCDFHOME/lib" -p "${cstarenv}" > /dev/null
	    conda env config vars set PATH="$(pwd):$ROMS_ROOT/Tools-Roms:$PATH" -p "${cstarenv}" > /dev/null
	    conda activate "${cstarenv}"

	    # 2. CHECKOUT EXTERNALS
	    echo "getting external packages as specified in Externals.cfg"
	    ./manage_externals/checkout_externals
	    
	fi
	# Alias command to go in .zshrc for future environment activation
 	CSTAR_ENV_ALIAS=\'"conda activate ${cstarenv}"\'

	compiler=gnu
	;;
    
    sdsc_expanse_intel)
	linux_hpc=true
	compiler=intel
	expected_syshost="expanse"
	env_file=additional_files/sdsc_expanse/expanse_environment.sh
	;;
    
    sdsc_expanse_gnu)
	echo "https://www.youtube.com/watch?v=ogwouE_Msd4"
	;;
    ncar_derecho_intel)
	linux_hpc=true
	compiler=intel
	expected_syshost="derecho"
	env_file=additional_files/ncar_derecho/derecho_environment.sh
	;;
    
    nersc_perlmutter_intel)
	linux_hpc=true
	compiler=intel
	expected_syshost="perlmutter"
	env_file=additional_files/nersc_perlmutter/perlmutter_environment_intel.sh
	;;
    nersc_perlmutter_gnu)
	linux_hpc=true
	compiler=gnu
	expected_syshost="perlmutter"
	env_file=additional_files/nersc_perlmutter/perlmutter_environment_gnu.sh
	;;    
    *)
	echo "Your machine $1 is not recognized or may not be supported. For a list of supported
	systems, run ./setup_cstar -h"
	exit 1
	;;
esac

if [ $linux_hpc = true ];then
    	if [ "$LMOD_SYSHOST" != "$expected_syshost" ];then
	    echo "You do not appear to be on $expected_syshost.
	    If you believe you are reading this message in error, please raise an issue:
	    https://github.com/CWorthy-ocean/C-Star/issues/new
	    Exiting setup
	    "
	    exit 1
	else
	    echo "compiling on $expected_syshost"
	fi
	#1. Set up environment
	ROMS_ROOT="$(pwd)/externals/ucla-roms/"
	cp "$env_file" "$HOME/.CSTAR"
	if ! grep -q "export ROMS_ROOT=${ROMS_ROOT}" "${HOME}/.CSTAR";then
	    echo "We are now modifying $HOME/.CSTAR"
	    echo "export ROMS_ROOT=${ROMS_ROOT}"                        >> "$HOME/.CSTAR"
	    echo "export MARBL_ROOT=$(pwd)/externals/MARBL/"            >> "$HOME/.CSTAR"
	    echo "export CSTAR_ROOT=$(dirname $(pwd))"                  >> "$HOME/.CSTAR"	    
	    echo "export CSTAR_SYSTEM=$1"                               >> "$HOME/.CSTAR"
	    echo 'export PATH=$PATH:${ROMS_ROOT}/Tools-Roms'":$(pwd)"   >> "$HOME/.CSTAR"
	fi
	source "${HOME}/.CSTAR"
	echo "nc-config"
	nc-config --prefix
	echo "nf-config"
	nf-config --prefix
	# Alias command to go in bashrc for future environment activation
	CSTAR_ENV_ALIAS=\'"source ${HOME}/.CSTAR"\'

	# 2. CHECKOUT EXTERNALS
	echo "getting external packages as specified in Externals.cfg"
	./manage_externals/checkout_externals

fi

# UNIVERSAL COMMANDS USING ABOVE CONFIGURED ENVIRONMENTS AND VARIABLES
################################################################################


# 2. COMPILE MARBL
cd ${MARBL_ROOT}/src
make ${compiler} USEMPI=TRUE
cd ${cstar_setupdir}

# 3. COMPILE ROMS/NHMG and ROMS/TOOLS-ROMS LIBRARIES

# i. Distribute universal ROMS makefiles
ls ${ROMS_ROOT}
cd additional_files/
rsync -av ROMS_Makefiles/* ${ROMS_ROOT}
mkdir ${ROMS_ROOT}/src/other
for f in {"check_alfabeta.F","check_rho_eos.F","int_r3d.F","sediment.F","t3dmix_GP.F","transp_nodes.F","u3dbc_new.F","visc3d_GP.F","visc3d_S_FS.F"};do
    if [ -e "${ROMS_ROOT}/src/${f}" ];then
	mv "${ROMS_ROOT}/src/${f}" "${ROMS_ROOT}/src/other/${f}"
    fi
done

## ii. make NHMG library
cd ${ROMS_ROOT}/Work
make COMPILER=${compiler} nhmg 

## iii. make Tools-Roms
cd ${ROMS_ROOT}/Tools-Roms
make COMPILER=${compiler}
#echo $PATH
# Manually specifying NETCDFF_{LIB,INC} as these are not correctly defined on Perlmutter with nf-config
#make NETCDFF_LIB="-L${NETCDFHOME}/lib -lnetcdff -lnetcdf" NETCDFF_INC="-I${NETCDFHOME}/include"
#echo $ROMS_ROOT

# 4. Establish access to the C-Star environment in future
SHRC="${HOME}/.${SHELL##*/}rc" # .bashrc or .zshrc on OSX
echo "All compilation steps successful!!" 
if ! grep -q "${CSTAR_ENV_ALIAS}" ${SHRC}; then
    read -p \
	 "
	 This setup script will now modify your ${SHRC} file to enable an environment for running C-Star.
      	 By default, an alias (cstar_env) will be added so that you can quickly set the environment up. Continue? (y/n)
	 " \
	 continuestring
    
    case ${continuestring} in
	y|Y)
	    echo "#SET UP ENVIRONMENT FOR RUNNING C-STAR:" >> "${SHRC}"
	    echo "################################################################################" >> "${SHRC}"
	    echo "alias cstar_env=${CSTAR_ENV_ALIAS}" >> "${SHRC}"
	    echo "################################################################################" >> "${SHRC}"

	    echo "--------------------------------------------------------------------------------"
	    echo "Your ${SHRC} file has been modified. In future, enter "
	    echo "cstar_env"
	    echo " to activate the environment for running C-Star."
	    echo "NOTE: This will not work until you either log back in or run"
	    echo "source ${SHRC}"
	    echo "--------------------------------------------------------------------------------"
	    ;;
	*)
	    echo "Your ${SHRC} file has not been modified. You will need to manually activate the C-Star environment using"
	    echo "${CSTAR_ENV_ALIAS}"
	    ;;
    esac
fi

